$ = window.$ = window.jQuery = require('jquery');
require('./bootstrap.min');
require('./bootstrap-select');
require('./ajax-bootstrap-select');
require('./jquery-ui.min');
require('./datepicker-de');
require('./jquery.webui-popover.min');
require('./slick.min');
require('./jquery.livequery');
require('./project');
require('./ajaxify');
require('./dayscheduler');